target 'ShoppingApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShoppingApp
	pod 'FMDB'
    pod 'ReachabilitySwift', '~> 3'
    pod 'SDWebImage/WebP'
    
end
